import random

monsters_lairs = {
    "Cherub": "chapel",
    "Fairy Queen": "garden",
    "Dark Vampire": "crypt",
    "Fallen Crusader": "chapel",
    "Father Rathburn": "chapel",
    "Fire Devil": "crypt",
    "Frost Serpent": "treehouse",
    "Fungal Beast": "garden",
    "Gargoyle": "chapel",
    "Giant Serpent": "garden",
    "Giant Slug Man": "cave",
    "Giant Termite": "treehouse",
    "Gorgon": "cave",
    "The Loner": "radio tower",
    "Hellhound": "cave",
    "Glowing Specter": "radio tower",
    "Lava Slime": "camp",
    "Little Deerpire": "treehouse",
    "Living Vines": "garden",
    "Lost Baby": "treehouse",
    "Lot": "chapel",
    "Magic Carpet": "radio tower",
    "Phoenix": "radio tower",
    "Rabid Cat": "camp",
    "Shadow Demon": "crypt",
    "The Prospector": "cave",
    "The Wise Man": "radio tower",
    "Treant": "garden",
    "Vampire Lord": "crypt",
    "Weeping Widow": "cave",
    "Were-Beaver": "treehouse",
    "Werewolf": "camp",
    "Witch": "camp",
    "Youthful Spirit": "crypt",
    "Zack the Zealot": "camp"
}